videobridge {
  http-servers {
    public {
      port = 9090
    }
  }

  websockets {
    enabled = true
    domain = "__MEET_DOMAIN__"
    tls = true
  }

  ice {
    udp {
      port = 10000
    }
  }

  nat {
    harvester {
      local-address = "__INTERNAL_IP__"
      public-address = "__EXTERNAL_IP__"
    }
  }

  stats {
    enabled = true
  }
}
