org.jitsi.videobridge.DISABLE_TCP_HARVESTER=true
org.jitsi.videobridge.TCP_HARVESTER_PORT=4443

org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=__INTERNAL_IP__
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=__EXTERNAL_IP__

org.jitsi.videobridge.ENABLE_STATISTICS=true
